package it.polimi.ingsw.View.StorageOfModelInformation;

public enum ModelChanges {
    CLOUDS_CHANGED,DISCARDPILE_CHANGED, ENTRANCE_CHANGED, STUDENTDINING_CHANGED,
    PROFDINING_CHANGED,ISLE_CHANGED,ISLELAYOUT_CHANGED,
    TOWERSTORAGE_CHANGED, CHARACTERCARD_CHANGED, COINS_CHANGED, GNRLRESERVE_CHANGED
}
